services:
  registry:
    image: registry:2
    ports:
      - "5001:5000"
    volumes:
      - ./registry/data:/var/lib/registry
      - /etc/letsencrypt/live/gensphere.io/fullchain.pem:/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/gensphere.io/privkey.pem:/certs/privkey.pem:ro
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/fullchain.pem
      REGISTRY_HTTP_TLS_KEY: /certs/privkey.pem
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
      REGISTRY_HTTP_TLS_MINIMUMTLS: tls1.2

  streamlit_app:
    build: ./app
    ports:
      - "8501:8501"
    depends_on:
      - registry
    environment:
      - REGISTRY_URL=https://registry.gensphere.io

  node_card_service:
    build: ./api/node_card
    ports:
      - "8000:8000"
    depends_on:
      - registry
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/

  jobs_service:
    build: ./api/jobs
    ports:
      - "8001:8001"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/

  job_executor:
    build: ./api/job_executor
    depends_on:
      - mongodb
      - registry
      - node_card_service
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      - REGISTRY_ADDRESS=registry.gensphere.io
      - DOCKER_HOST=unix:///var/run/docker.sock

  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/mongodb_data:/data/db

  agents_service:
    build: ./api/agents
    ports:
      - "8002:8002"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
