version: '3'
services:
  registry:
    image: registry:2
    ports:
      - "5001:5000"
    volumes:
      - ./registry/data:/var/lib/registry
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: "true"

  streamlit_app:
    build: ./app
    ports:
      - "8501:8501"
    depends_on:
      - registry
    environment:
      - REGISTRY_URL=http://registry:5000
