services:
  registry:
    image: registry:2
    ports:
      - "5001:5000"
    volumes:
      - ./registry/data:/var/lib/registry
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: "true"

  streamlit_app:
    build: ./app
    ports:
      - "8501:8501"
    depends_on:
      - registry
    environment:
      - REGISTRY_URL=http://registry:5000

  api_service:
    build: ./api
    ports:
      - "8000:8000"
    depends_on:
      - registry
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/

  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/mongodb_data:/data/db
